Algoritmo "FunçaoPotencia"
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Jovana Matos
// Data atual  : 14/02/2024
Var
  X,Y, Resposta : real
   Funcao Potencia (n1,n2 : real ): real
   var res : real
   inicio
   res <- n1^n2
   retorne res
   fimfuncao
   


Inicio
      X <- 5
      Y <- 2
      Resposta <- Potencia(X, Y)
      escreva ("O total é", Resposta)

Fimalgoritmo