Algoritmo "Parametros"
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 07/02/2024
Var
a,b,c : caracter
Procedimento Gerador(d,j,f: caracter)
var
g,h,i: caracter
Inicio
g <- d
h <- j
i <- f
Escreval (g)
Escreval (h)
Escreval (i)
FimProcedimento
Inicio
 a <- ("**********************************")
 b <- ("         Aprendendo Portugol      ")
 c <- ("**********************************")
 Gerador (a,b,c)
 //Escreva (a)

Fimalgoritmo