Algoritmo "Procedimento")
// Autor(a)    : Jovana Matos
// Data atual  : 17/01/2024
Var
   X, y: Inteiro
Procedimento soma (var A, B: Inteiro)  //valor por referencia
Inicio
      A <- A + 1
      B <- B + 2
      EscrevaL("Valor de A = ", A)
      EscrevaL("Valor de B = ", B)
      EscrevaL("Soma A + B= ", A+B )
FimProcedimento
Inicio
       X <- 4
       Y <- 8
       Soma (X, y)
       EscrevaL ("Valor de X = ", X)
       EscrevaL ("Valor de Y = 2" Y)
Fimalgoritmo