Algoritmo "seqFibonacci"

Var
   Penultimo,Ultimo,Proximo,Contagem : inteiro

Inicio
      escreva ("0")
      escreva (" 1")
      Penultimo <- 0
      Ultimo <- 1
      Para Contagem := 3 ate 15 faca
         Proximo := Ultimo + Penultimo
          escreva (Proximo)
          
          
          
          Penultimo := Ultimo
          Ultimo := Proximo


      FimPara

Fimalgoritmo