Algoritmo "SomaParametosReferencia"
// Autor(a)    : Jovana Matos
// Data atual  : 03/01/2024
Var
 X, Y : Inteiro
Procedimento Soma (A, B: Inteiro)
Inicio
 A <- A + 1
 B <- B + 1
 EscrevaL("Valor de A = ", A)
 EscrevaL("Valor de B = ", B)
 EscrevaL("Valor de A + B = ", A+B)
FimProcedimento
Inicio
 X <- 4
 Y <- 8
 Soma (X, Y)
 Escreval ("Valor de X = ", X)
 Escreval ("Valor de Y = ", Y)
Fimalgoritmo